if["$(BUILD)" = "debug"]; then echo "build debug"; else echo "build release"; fi
default: all
        
.DEFAULT:
	@echo "execute default" $@
    
install:
	@echo "execute install"
    
.PHONY: install