#! /bin/csh -f
set INCLUDE = /www/redisResourceInAction/01-SDS
set REDISLIB = $INCLUDE/libredis.a
set LIBRARIES = ($REDISLIB -lX11 -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
